phrase:
  project_id: 8c5c54fe978485a855aa71ccacc4a373
  file_format: json

  push:
    sources:
    - file: ./locales/<locale_code>/translation.json
      params:
        update_translations: true
        autotranslate: true
        file_encoding: "UTF-8"
        

  pull:
    targets:
    - file: ./locales/<locale_code>/translation.json
      params:
        include_empty_translations: true
        include_translated_keys: true
        include_unverified_translations: true
      
